name: slurmlib
channels:
    - conda-forge
    - nodefaults
dependencies:
    - mamba>=1.0.0
    - conda-lock>=1.2.1
    - python>=3.11
    - cookiecutter>=2.1.1
    - pip>=22.2.20
    - pip:
          - python-dotenv>=0.21.0
          - pyprojroot>=0.2.0
          # Development dependencies
          - bump2version>=1.0.1 # version controls
          - pre-commit>=2.12.0 # hooks for applying linters on commit
          - tox>=3.20.1 # test env management
          - tox-conda>=0.2.0 # test conda env management
          - pytest>=6.2.4 # code testing package
          - pytest_cov>=4.0.0 # test coverage
          - flake8>=5.0.4 # code analysis
          - isort>=5.10.1 # sort imports
          - black>=22.10.0 # code formatting
          - mypy>=0.982 # type checking
          - mkdocs>=1.4.2 # code documentation
          - mkdocs-include-markdown-plugin>=3.9.1
          - mkdocs-material>=8.5.8
          - mkdocstrings[python]>=0.19.0
          - mkdocs-autorefs>=0.4.1
          # Project specific
          - joblib
          - pyslurm
